# Generated by Django 5.1.1 on 2024-09-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bougie',
        ),
        migrations.DeleteModel(
            name='Crochet',
        ),
    ]
