# Generated by Django 5.1.1 on 2024-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BougieArtisanale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('couleur', models.CharField(max_length=20)),
                ('taille', models.CharField(max_length=20)),
                ('forme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BougieGourmande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('couleur', models.CharField(max_length=20)),
                ('taille', models.CharField(max_length=20)),
                ('forme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bruleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('couleur', models.CharField(max_length=20)),
                ('taille', models.CharField(max_length=20)),
                ('forme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrochetDoudou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('couleur', models.CharField(max_length=20)),
                ('taille', models.CharField(max_length=20)),
                ('matiere', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fondant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('couleur', models.CharField(max_length=20)),
                ('taille', models.CharField(max_length=20)),
                ('forme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FondantCremeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('couleur', models.CharField(max_length=20)),
                ('taille', models.CharField(max_length=20)),
                ('forme', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CrochetDoudour',
        ),
        migrations.RemoveField(
            model_name='crochetanimaux',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crochetlapinou',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crochetportecles',
            name='name',
        ),
        migrations.AddField(
            model_name='crochetanimaux',
            name='couleur',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetanimaux',
            name='description',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetanimaux',
            name='matiere',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetanimaux',
            name='nom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetanimaux',
            name='taille',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetlapinou',
            name='couleur',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetlapinou',
            name='description',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetlapinou',
            name='matiere',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetlapinou',
            name='nom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetlapinou',
            name='taille',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetportecles',
            name='couleur',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetportecles',
            name='description',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetportecles',
            name='matiere',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetportecles',
            name='nom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetportecles',
            name='taille',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
