# Generated by Django 5.1.1 on 2024-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_bougieartisanale_bougiegourmande_bruleurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bougieartisanale',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bougiegourmande',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bruleurs',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetanimaux',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetdoudou',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetlapinou',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crochetportecles',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondant',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondantcremeux',
            name='image_base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
